remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: false
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: true
 month: false
 week: false
 24 hours: false

positions:
  - Software Developer
  - FrontEnd Developer
  - UI Developer
  - Javascript Developer

locations:
  - India

distance: 100

companyBlacklist:
  - Cisco
  - Wipro

titleBlacklist:
  - Sales
  - Marketing